site_name: R1a Docs
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: img/RR-white-side.svg
  favicon: img/favicon.png
  palette:
    scheme: default
    primary: black
  features:
    - instant
  custom_dir: 'theme'
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: '©2020 Rock Robotic Inc.'
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rockrobotic
repo_url: https://github.com/rockrobotic/rock-doc
plugins:
  - search
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: False
    - def_list
    - footnotes
    - meta
    - toc:
        permalink: True
    - pymdownx.details
    - attr_list
nav:
  - Introduction: index.md
  - Quickstart:
    - First Setup: quickstart/first-setup.md
    - Web Interface: quickstart/web-interface.md
  - Tutorials:
    - Terrain Following Mission: tutorials/Terrain-Following-Tutorial.md
  - Drone Setup:
    - Matrice 300 RTK: drone-setup/m300.md
    - Matrice 210: drone-setup/m210.md
    - Matrice 600: drone-setup/m600.md
  - Geometry Configuration: geometry-configuration.md
  - Connectivity: connectivity.md
  - Firmware Update: firmware.md
google_analytics:
  - UA-173543820-3
  - auto
