site_name: ROCK robotic Docs
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: img/rock-robotic-logo.png
  favicon: img/favicon-black-R.png
  palette:
    scheme: default
    primary: black
  features:
    - instant
  custom_dir: 'theme'
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: '©2020 Rock Robotic Inc.'
site_description: 'Accuracy. Reliability. Simplicity.'
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rockrobotic
repo_url: https://github.com/rockrobotic/rock-doc
plugins:
  - search
  - print-site:
      add_cover_page: true
      cover_page_template: "docs/assets/templates/custom_cover_page.tpl"
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: False
    - def_list
    - footnotes
    - meta
    - toc:
        permalink: True
    - pymdownx.details
    - attr_list
nav:
  - Introduction: index.md
  - Placing the Base: placing-the-base/settingup.md
  - Calibration: Calibration/Calibration.md
  - Mission Planning: mission-planning/mission-planning.md
  - Quickstart:
    - First Setup: quickstart/first-setup.md
    - Web Interface: quickstart/web-interface.md
    - Flight Checklist: quickstart/checklist.md
  - Rock Robotic Pre-processing:
    - Introduction: pre-processing/introduction.md
    - Trajectory Processing: pre-processing/trajectory-processing.md
    - Pointcloud Processing: pre-processing/point-cloud-processing.md
    - Pointcloud Colorizing: pre-processing/colorizing.md
  - Rock Robotic Cloud:
    - Getting Started: rock-cloud/getting-started.md
    - Project: rock-cloud/project.md
    - Process: rock-cloud/process.md
    - Deliverables: rock-cloud/deliverables.md
    - WebGL: rock-cloud/webgl.md
  - Tutorials:
    - Placing the Base: tutorials/Placing-the-Base.md
    - Geometry Configuration: tutorials/geometry-configuration.md
    - Connectivity: tutorials/connectivity.md
    - Firmware Update: tutorials/firmware.md
    - Advanced Mission Planning: tutorials/advanced-mission.md
    - Terrain Following: tutorials/Terrain-Following-Tutorial.md
    - R1A Boresighting: tutorials/r1a-boresighting.md
    - USB Drive: tutorials/usb.md
  - Drone Setup:
    - Matrice 300 RTK: drone-setup/m300.md
    - Matrice 210: drone-setup/m210.md
    - Matrice 600: drone-setup/m600.md
    - Freefly Alta-X: drone-setup/alta-x.md
    - Other Drone Systems: drone-setup/other.md

google_analytics:
  - UA-173543820-3
  - auto
