site_name: ROCK robotic Docs
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: img/rock-robotic-logo.png
  favicon: img/favicon-black-R.png
  palette:
    scheme: default
    primary: black
  features:
    - instant
  custom_dir: 'theme'
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: '©2021 Rock Robotic Inc.'
site_description: 'Accuracy. Reliability. Simplicity.'
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rockrobotic
repo_url: https://github.com/rockrobotic/rock-doc
plugins:
  - search
  - print-site:
      add_cover_page: true
      cover_page_template: "docs/assets/templates/custom_cover_page.tpl"
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: False
    - def_list
    - footnotes
    - meta
    - toc:
        permalink: True
    - pymdownx.details
    - attr_list
nav:
  - Introduction: index.md
  - Quickstart:
    - Placing the Base: placing-the-base/settingup.md
    - Mission Planning: mission-planning/mission-planning.md
    - First Setup: quickstart/first-setup.md
    - Take Flight: Calibration/Take-flight.md
    - Flight Checklist: quickstart/checklist.md
  - LiDAR Details:
      - Understanding the Payload: lidar-details/understanding-payload.md
      - Web Interface: lidar-details/web-interface.md
      - USB Drive: lidar-details/usb.md
      - Firmware Update: lidar-details/firmware.md
      - Geometry Configuration: lidar-details/geometry-configuration.md
      - Connectivity: lidar-details/connectivity.md
      - Boresighting: lidar-details/boresighting.md
      - Camera Boresighting: lidar-details/camera-boresighting.md
      - R2A Physical Dimensions: lidar-details/r2a-physical.md
      - GNSS Antenna Datasheet: lidar-details/gnss-antenna-specs.md
  - Rock Robotic Pre-processing:
    - Introduction: pre-processing/introduction.md
    - Embedded Trajectory Processing: pre-processing/embedded-trajectory-processing.md
    - Stand-alone Trajectory Processing: pre-processing/trajectory-processing.md
    - Pointcloud Processing: pre-processing/point-cloud-processing.md
    - Pointcloud Colorizing: pre-processing/colorizing.md
  - Rock Robotic Cloud:
    - Getting Started: rock-cloud/getting-started.md
    - Project: rock-cloud/project.md
    - Process: rock-cloud/process.md
    - Deliverables: rock-cloud/deliverables.md
    - WebGL: rock-cloud/webgl.md
    - Custom Site Projections: rock-cloud/exporting-in-other-projection-systems.md
  - Tutorials:
    - Placing the Base: tutorials/Placing-the-Base.md
    - No GUI Flight: tutorials/flight-no-gui.md
    - Advanced Mission Planning: tutorials/advanced-mission.md
    - Terrain Following: tutorials/Terrain-Following-Tutorial.md
  - Drone Setup:
    - Matrice 300 RTK: drone-setup/m300.md
    - Matrice 210: drone-setup/m210.md
    - Matrice 200: drone-setup/m200.md
    - Matrice 600: drone-setup/m600.md
    - Freefly Alta-X: drone-setup/alta-x.md
    - Other Drone Systems: drone-setup/other.md

google_analytics:
  - UA-173543820-3
  - auto
